config/routes.rb
Rails.application.routes.draw do

  get '/products' => 'products#index', as: :products
  get '/products/:id' => 'products#show', as: :product
  get '/products/search/autocomplete' => 'products#autocomplete', as: :products_autocomplete

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'application#home'

  get '/home' => 'application#home', as: :home
  get '/about' => 'application#about', as: :about
  get '/contact' => 'application#contact', as: :contact

end

app/models/product.rb
class Product < ActiveRecord::Base
  scope :active, -> { where(active: true) }
  is_impressionable counter_cache: true, column_name: :page_views
  has_and_belongs_to_many :categories
  belongs_to :affiliate_program
  belongs_to :merchant
  belongs_to :brand

  # include ElasticsearchSearchable ##this has been replaced by searchkick
  searchkick text_start: [:product_name], autocomplete: ['product_name']

  def search_data
    as_json(only: [:product_name, :description, :keywords, :search_price, :currency, :active]).merge(brand: brand.name).merge(merchant: merchant.name)
  end

  def last_updated_display
    if self.last_updated.nil?
      self.updated_at
    else
      self.last_updated
    end
  end

  def currency_price
    if self.currency == 'GBP'
      '£%.2f' % self.search_price.to_s
    else
      '%$%.2f' % (self.currency self.search_price.to_s)
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  impressionist actions: [:show]

  # GET /products
  # GET /products.json
  def index
    if params[:search].present?
      query = params[:search][:q].present? ? params[:search][:q] : '*'
      @search = execute_search(query, params[:page])
    else
      @search = execute_search('*', params[:page])
    end
  end

  def execute_search(query, page, per_page = 20)
    Product.search(query, page: page, per_page: per_page, facets: [:brand, :merchant])
  end

  #
  # def search_params(params={})
  #   return [nil,nil] if params.blank? || params[:search].blank?
  #   p = params[:search].dup
  #   q = p.delete(:q)
  #   [q, p]
  # end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def autocomplete
    render json: Product.search(params[:search][:q], fields: [{product_name: :text_start}], limit: 10).map(&:product_name)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit( :merchant, :affiliate_program, :brand, :active, :notes, :aw_product_id, :aw_deep_link, :aw_image_url, :aw_thumb_url, :merchant_product_id, :merchant_category, :merchant_image_url, :merchant_deep_link, :product_name, :description, :parent_product_id, :brand_name, :brand_id, :model_number, :colour, :condition, :keywords, :product_type, :promotional_text, :specifications, :currency, :search_price, :display_price, :rrp_price, :saving, :store_price, :delivery_cost, :delivery_restrictions, :delivery_time, :in_stock, :is_for_sale, :pre_order, :valid_from, :valid_to, :web_offer, :average_rating, :reviews, :rating, :last_updated)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :affiliate_program %><br>
    <%= f.text_field :affiliate_program %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :deep_link %><br>
    <%= f.text_area :deep_link %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :merchant_category %><br>
    <%= f.text_field :merchant_category %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_area :image_url %>
  </div>
  <div class="field">
    <%= f.label :ean %><br>
    <%= f.number_field :ean %>
  </div>
  <div class="field">
    <%= f.label :upc %><br>
    <%= f.number_field :upc %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br>
    <%= f.number_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :mpn %><br>
    <%= f.text_field :mpn %>
  </div>
  <div class="field">
    <%= f.label :parent_product_id %><br>
    <%= f.number_field :parent_product_id %>
  </div>
  <div class="field">
    <%= f.label :brand_name %><br>
    <%= f.text_field :brand_name %>
  </div>
  <div class="field">
    <%= f.label :model_number %><br>
    <%= f.text_field :model_number %>
  </div>
  <div class="field">
    <%= f.label :basket_link %><br>
    <%= f.text_area :basket_link %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_area :colour %>
  </div>
  <div class="field">
    <%= f.label :commission_group %><br>
    <%= f.text_field :commission_group %>
  </div>
  <div class="field">
    <%= f.label :condition %><br>
    <%= f.text_field :condition %>
  </div>
  <div class="field">
    <%= f.label :dimensions %><br>
    <%= f.text_area :dimensions %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br>
    <%= f.text_area :keywords %>
  </div>
  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :product_type %><br>
    <%= f.text_area :product_type %>
  </div>
  <div class="field">
    <%= f.label :product_weight %><br>
    <%= f.text_area :product_weight %>
  </div>
  <div class="field">
    <%= f.label :promotional_text %><br>
    <%= f.text_area :promotional_text %>
  </div>
  <div class="field">
    <%= f.label :specifications %><br>
    <%= f.text_area :specifications %>
  </div>
  <div class="field">
    <%= f.label :warranty %><br>
    <%= f.text_area :warranty %>
  </div>
  <div class="field">
    <%= f.label :currency %><br>
    <%= f.text_field :currency %>
  </div>
  <div class="field">
    <%= f.label :delivery_cost %><br>
    <%= f.text_field :delivery_cost %>
  </div>
  <div class="field">
    <%= f.label :delivery_cost %><br>
    <%= f.text_field :delivery_cost %>
  </div>
  <div class="field">
    <%= f.label :delivery_restrictions %><br>
    <%= f.text_area :delivery_restrictions %>
  </div>
  <div class="field">
    <%= f.label :delivery_time %><br>
    <%= f.text_field :delivery_time %>
  </div>
  <div class="field">
    <%= f.label :in_stock %><br>
    <%= f.check_box :in_stock %>
  </div>
  <div class="field">
    <%= f.label :is_for_sale %><br>
    <%= f.check_box :is_for_sale %>
  </div>
  <div class="field">
    <%= f.label :pre_order %><br>
    <%= f.check_box :pre_order %>
  </div>
  <div class="field">
    <%= f.label :stock_quantity %><br>
    <%= f.number_field :stock_quantity %>
  </div>
  <div class="field">
    <%= f.label :rrp_price %><br>
    <%= f.text_field :rrp_price %>
  </div>
  <div class="field">
    <%= f.label :rrp_price %><br>
    <%= f.text_field :rrp_price %>
  </div>
  <div class="field">
    <%= f.label :saving %><br>
    <%= f.text_area :saving %>
  </div>
  <div class="field">
    <%= f.label :store_price %><br>
    <%= f.text_field :store_price %>
  </div>
  <div class="field">
    <%= f.label :store_price %><br>
    <%= f.text_field :store_price %>
  </div>
  <div class="field">
    <%= f.label :valid_from %><br>
    <%= f.date_select :valid_from %>
  </div>
  <div class="field">
    <%= f.label :valid_to %><br>
    <%= f.date_select :valid_to %>
  </div>
  <div class="field">
    <%= f.label :web_offer %><br>
    <%= f.check_box :web_offer %>
  </div>
  <div class="field">
    <%= f.label :merchant_image %><br>
    <%= f.text_area :merchant_image %>
  </div>
  <div class="field">
    <%= f.label :merchant_thumb %><br>
    <%= f.text_area :merchant_thumb %>
  </div>
  <div class="field">
    <%= f.label :thumb_url %><br>
    <%= f.text_area :thumb_url %>
  </div>
  <div class="field">
    <%= f.label :average_rating %><br>
    <%= f.text_area :average_rating %>
  </div>
  <div class="field">
    <%= f.label :reviews %><br>
    <%= f.text_area :reviews %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.text_area :rating %>
  </div>
  <div class="field">
    <%= f.label :last_updated %><br>
    <%= f.datetime_select :last_updated %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_left_column.erb
<!--<div class="row">-->

  <div class="col-sm-4">

    <div class="sidebar ">
      <br />

      <%= form_tag products_path, method: :get, class: 'form-inline mini', style: "margin-bottom: 0px;" do %>

      <div class="row ">

        <div class="col-sm-11">

          <div class="panel panel-default">
            <div class="panel-heading">Filter Results</div>
            <div class="panel-body">

              <!--<div class="form-group">-->
                <!--<input type="search" class="form-control" name="search[q]" placeholder="Search" value="<%= (params[:search].present? && params[:search][:q].present?) ? params[:search][:q] : "" %>">-->
              <!--</div>-->

                  <div class='form-group'>
                    <!--<div class="col-sm-6">-->
                      <label>Brand</label>
                    <!--</div>-->
                      <!--<div class="col-sm-6">-->
                      <select class='form-control facet_select' name="search[brand]">
                      <% @search.facets['brand']['terms'].each do |t| %>
                           <% selected = (params[:search].present? && params[:search][t['term']].present? && params[:search][t['term']]==t['term']) ? true : false %>
                          <option data-selected="<%= selected %>" value="<%= t['term'] %>" <%= selected ? "selected" : "" %> >
                            <%= t['term'] %>
                            (<%= t['count'] %>)
                          </option>
                      <% end %>
                      </select>
                      <!--</div>-->
                  </div>

              <div class='form-group'>
                <!--<div class="col-sm-6">-->
                <label>Merchant</label>
                <!--</div>-->
                <!--<div class="col-sm-6">-->
                <select class='form-control facet_select' name="search[merchant]">
                  <% @search.facets['merchant']['terms'].each do |t| %>
                      <% selected = (params[:search].present? && params[:search][t['term']].present? && params[:search][t['term']]==t['term']) ? true : false %>
                      <option data-selected="<%= selected %>" value="<%= t['term'] %>" <%= selected ? "selected" : "" %> >
                        <%= t['term'] %>
                        (<%= t['count'] %>)
                      </option>
                  <% end %>
                </select>
                <!--</div>-->
              </div>
              <!--<div class="row filter-row">-->
                <!--<div class="col-sm-12">-->
                  <!--<label>Price range</label>-->
                <!--</div>-->
                <!--<div class="col-sm-6">-->
                  <!--<div class="input-group">-->
                    <!--<span class="input-group-addon">$</span>-->
                    <!--<input type="email" class="form-control price-input" placeholder="min" />-->
                  <!--</div>-->
                <!--</div>-->
                <!--<div class="col-sm-6">-->
                  <!--<div class="input-group">-->
                    <!--<span class="input-group-addon">$</span>-->
                    <!--<input type="email" class="form-control price-input" placeholder="max" />-->
                  <!--</div>-->
                <!--</div>-->
              <!--</div>-->


              <div class='form-group'>
                <button type="submit" class="btn btn-primary pull-right" id="search_btn">Filter</button>
              </div>




            </div>
          </div>




        </div>
      </div>
    </div>

      <% end %>
  </div>
<!--</div>-->

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% provide(:title, "Results") %>
<% provide(:description, "Search and compare pricing on thousands of cycling products from leading cycling brands, in one place") %>
<%= render 'layouts/jumbotron_well' %>
<div class="container">

  <br />
  <div class="row">
  <div class="col-sm-12">
  <!--<ol class="breadcrumb">-->
  <!--<li><a href="#">Home</a></li>-->
  <!--&lt;!&ndash;<li><a href="#">Vehicles</a></li>&ndash;&gt;-->
  <!--&lt;!&ndash;<li class="active">Cars</li>&ndash;&gt;-->
  <!--&lt;!&ndash;<li class="active">4,699 results for <strong>"Cars"</strong> in London</li>&ndash;&gt;-->
  <!--</ol>-->
  </div>
  </div>

  <div class="row">

<!--Change this to sm-8 when rendering the sidebar -->
    <%= render 'products/left_column' %>

    <div class="col-sm-8 pull-right listings">

      <div class="row listing-row" style="margin-top: -10px;">
        <div class="pull-left">
          <strong>Today, <%= Time.now.strftime("%A #{Time.now.day.ordinalize} %B") %></strong>
          <br>
          <small><%= "Page #{@search.current_page} of #{@search.total_pages} (#{@search.total_count} results)" %></small>
        </div>
        <!--<div class="pull-right">-->
          <!--<span style="">Sort by:&nbsp;&nbsp;&nbsp;</span>-->
          <!--<a href="#"  data-toggle="tooltip" data-placement="top" title="Sort by relevance"> Relevance <i class="fa fa-chevron-up"></i></a>-->
          <!--<a href="#" data-toggle="tooltip" data-placement="top" title="Sort from lowest to highest price"> Price <i class="fa fa-chevron-down"></i></a>-->
        <!--</div>-->
      </div>

      <% @search.each do |product| %>

          <div class="row  listing-row">

            <div class="col-sm-2">
              <%= link_to image_tag(product.aw_thumb_url, alt: product.product_name), product_path(product.id), class: 'thumbnail'%>
            </div>

            <div class="col-sm-10">
              <h3>
                <%= link_to "#{product.product_name} - <strong> #{product.display_price}</strong>".html_safe, product_path(product.id)%>
              </h3>
              <p class="muted">
                Brand <strong><%= product.brand.name %> </strong> |
                Vendor <strong><%= product.merchant.name %></strong>
              </p>
              <p><%= product.description.force_encoding("utf-8") %></p>
              <p class="ad-description muted">
              <p>
                <br>
            <span class="classified_links pull-right">
              <%= link_to 'Details', product_path(product.id), class: 'link-info underline'%>&nbsp;
            &nbsp;
              <%= link_to 'Buy From Vendor', product.aw_deep_link, class: 'btn btn-warning', rel: 'nofollow'%>&nbsp;
            </span>
              </p>
            </div>

          </div>

      <% end %>


      <div class="pull-right">
        <%= paginate @search %>
      </div>


      </div>
    </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/original_index.html.erb
<% provide(:title, "Results") %>
<%= render 'layouts/jumbotron_well' %>

<div class="container">

<br />
<div class="row">
<!--<div class="col-sm-12">-->
<!--<ol class="breadcrumb">-->
<!--<li><a href="#">Home</a></li>-->
<!--&lt;!&ndash;<li><a href="#">Vehicles</a></li>&ndash;&gt;-->
<!--&lt;!&ndash;<li class="active">Cars</li>&ndash;&gt;-->
<!--&lt;!&ndash;<li class="active">4,699 results for <strong>"Cars"</strong> in London</li>&ndash;&gt;-->
<!--</ol>-->
<!--</div>-->
</div>

<div class="row">

<div class="col-sm-12 listings">

<div class="row listing-row" style="margin-top: -10px;">
<div class="pull-left">
<strong>Today, <%= Time.now.strftime("%A #{Time.now.day.ordinalize} %B") %></strong>
<br>
<small><%= "Page #{@products.current_page} of #{@products.total_pages} (#{@products.total_count} results)" %></small>
</div>
<div class="pull-right">
<!--<span style="">Sort by:&nbsp;&nbsp;&nbsp;</span>-->
<!--<a href="#"  data-toggle="tooltip" data-placement="top" title="Sort from newest to oldest"> Date <i class="fa fa-chevron-up"></i></a>-->
<!--<a href="#" data-toggle="tooltip" data-placement="top" title="Sort from lowest price to highest price"> Price <i class="fa fa-chevron-down"></i></a>-->
</div>
</div>


<div class="pull-right">
<%= paginate @products %>
</div>

</div>
</div>
</div>

app/views/products/show.html.erb
<% provide(:title, @product.product_name) %>
<% provide(:description, @product.description[0,70]) %>
<%= render 'layouts/jumbotron_well' %>
<div class="container" id="listings-page">
  <div class="row">
    <div class="col-sm-12 listing-wrapper listings-top listings-bottom">
      <br />
      <br />

      <div class="row">

      </div>

      <div class="row">

        <div class="col-sm-7">
          <h1><%= @product.product_name %></h1>
          <!--<p>Brand: <%= @product.brand.name %></p>-->
        </div>


        <div class="col-sm-5">

          <p class="price"><%= @product.currency_price %></p>

        </div>

      </div>

      <div class="row">

      <div class="col-sm-7">
        <div class="row">
          <!--Share buttons-->
        </div>
      </div>


    </div>
    <hr />


      <div class="row">

        <div class="col-sm-7">

          <h3>Product Details</h3>

          <div class="row">

            <div class="col-xs-6">
              <table class="table">

                <tbody>
                <tr>
                  <th>Brand</th>
                  <td><%= @product.brand.name %></td>
                </tr>
                <tr>
                  <th>Vendor</th>
                  <td><%= @product.merchant.name %></td>
                </tr>

                </tbody>
              </table>
            </div>
            <div class="col-xs-6">
              <table class="table">

                <tbody>
                <tr>
                  <th>Price</th>
                  <td><%= @product.currency_price %></td>
                </tr>
                <tr>
                  <th></th>
                  <td></td>
                </tr>

                </tbody>
              </table>
            </div>
          </div>
          <p>
            <%= @product.description.force_encoding("utf-8") %>
            <br />
            <br />
            <%= link_to 'Buy From Vendor', @product.aw_deep_link, class: 'btn btn-warning', rel: 'nofollow'%>
          </p>

          <!--<p>-->
            <!--<span class="classified_links ">-->
                <!--<a class="link-info" href="#"><i class="fa fa-share"></i> Share</a>&nbsp;-->
                <!--<a class="link-info " href="#"><i class="fa fa-star"></i> Add to favorites</a>-->
                <!--&nbsp;<a class="link-info " href="#"><i class="fa fa-envelope-o"></i> Contact</a>-->
                <!--&nbsp;<a class="link-info fancybox-media" href="http://maps.google.com/?ll=48.85796,2.295231&spn=0.003833,0.010568&t=h&z=17"><i class="fa fa-map-marker"></i> Map</a></span>-->
          <!--</p>-->

        </div>

        <div class="col-sm-5 center zoom-gallery">
          <div class="row center">

            <div class="col-sm-12">
              <%= image_tag(@product.aw_image_url, alt: @product.product_name, class: 'raised img-responsive', style: "margin: 0 auto") %>
              <br />
            </div>
          </div>
          <br />
          <div class="col-sm-12" style="text-align: center; margin: 0 auto">
            <%= link_to 'Buy From Vendor', @product.aw_deep_link, class: 'btn btn-warning', rel: 'nofollow'%>
            <br />
            <br />
            <p><%= @product.currency_price %></p>
          </div>
          <br />

        </div>

      </div>

      <!--END LISTING-->

    </div>
  </div>

</div>